### ISSUE TITLE
Tickets are available

### ISSUE THREAD

**Issue by ccjjmartin** [TexasCamp/2019.texascamp.org#10]
Added ticket options but we didn't add benefits of each ticket

**Comment by ccjjmartin** [comment]
News Post Created:
https://backend2019.texascamp.org/news/tickets-get-your-tickets

2019 Texas Camp Questionnaire Created (needs review): https://docs.google.com/forms/d/16uxTCuVu7WJ6PWsiwWp5PgYK2tKoE7_rJoqEbR3g024/edit

Irma Martin Worked on Mail Chimp (needs review):
https://us14.admin.mailchimp.com/campaigns/edit?id=680217

**Comment by rocketeerbkw** [comment]
news LGTM

**Comment by rocketeerbkw** [comment]
I created a new newsletter that uses our template with the same content (just adjusted for styles): review: https://us14.admin.mailchimp.com/campaigns/edit?id=680397

**Comment by ccjjmartin** [comment]
Reviewing the new newsletter now, this isn't a blocker for the site to go live so I am closing.
