### ISSUE TITLE
Cache busting frontend JS

### ISSUE THREAD

**Issue by rocketeerbkw** [TexasCamp/2019.texascamp.org#19]
When deploying new code, it's pretty common that pages won't render and throw an error about invalid chunks or something.

This is due to the browser caching the JS. Should find some mechanism that fixes this for new deploys.

I assume that the build script just saves to the same filenames for each build, perhaps it would be easy to change to a date or hash based filename instead.

**Comment by ccjjmartin** [comment]
Testing an upgrade to the webpack-flush-chunks package to see if it solves this issue.

**Comment by ccjjmartin** [comment]
The upgrade to the package didn't work, I am going to revert it on dev.  This page is the best example I have locally: https://frontend-2019-texascamp-dev.us.amazee.io/san-antonio

It works in incognito but doesn't work on my main browser right now.

**Comment by ccjjmartin** [comment]
Upgraded the amazee/react-scripts package and this is now fixed.
