### ISSUE TITLE
Update submit a session

### ISSUE THREAD

**Issue by rocketeerbkw** [TexasCamp/2019.texascamp.org#2]
Make sure content on submit session page is correct.

https://backend2019.texascamp.org/submit-session

**Comment by ccjjmartin** [comment]
Updated content to match our decision to allow lightning talks, panels, and trainings.

Also sent in a PR #13 , once the PR is merged this one in my mind can be closed.

**Comment by ccjjmartin** [comment]
Actually, I want to include a page with an example submission, I will follow up with Charles tomorrow.

**Comment by rocketeerbkw** [comment]
I don't think this needs it's own page, can go on the submit-session after the "submit session" CTA

**Comment by ccjjmartin** [comment]
Sounds good to me to add it to the same page

**Comment by ccjjmartin** [comment]
Added an example, Charles is going to verify with Mark it is ok to spotlight his submission.  Closing.
