### ISSUE TITLE
Free attendees appearing on open collective

### ISSUE THREAD

**Issue by ccjjmartin** [TexasCamp/2019.texascamp.org#23]
Task: Free attendees appearing on open collective

Email open with OC

**Comment by ccjjmartin** [comment]
@rocketeerbkw Moving this discussion over here.  The OC response was to create a free ticket on OC and let people register that way.  I saw you created a meetup event.  Should we use meetup to manage the attendee list since OC doesn't have this capability?  Other thoughts?

**Comment by rocketeerbkw** [comment]
@ccjjmartin what does "manage the attendee" list mean to you? The meetup event was just for marketing purposes and has the same limit as OC, RSVPs are open to anyone.

If you are asking how do we get a list of ppl to check at "at the door", I assumed we'd have a spreadsheet. We can export the attendees who paid on OC via CSV/JSON and we can manually track volunteer/sponsor tickets in there.

**Comment by rocketeerbkw** [comment]
We decided to make free tickets on OC and just pay attention to who signs up
