### ISSUE TITLE
Submissions page errors

### ISSUE THREAD

**Issue by ccjjmartin** [TexasCamp/2019.texascamp.org#29]
https://adug.slack.com/archives/C2LCYD38V/p1566837746082600

**Comment by ccjjmartin** [comment]
It was decided that we would switch to using a hard coded header and beyond that it is likely a browser plugin causing issues so we would recommend to users that they clear the browser cache and disable plugins.

**Comment by stephencapellic** [comment]
The above Slack link goes to my issue report. I was using Chrome on OSX. Also having the problem using Safari on OSX.

**Comment by stephencapellic** [comment]
I'd like to submit my session :-)

**Comment by stephencapellic** [comment]
Thank you!
