### ISSUE TITLE
Sessions page bug

### ISSUE THREAD

**Issue by ccjjmartin** [TexasCamp/2019.texascamp.org#46]
## Reproduce:
1) Make your screen really short and find a page that is really long that links to a session: https://2019.texascamp.org/schedule

2) Scroll to the bottom of the page and select a link that goes to a sessions page

3) Notice that the session is also scrolled down and the author bio is the only thing visible (you can scroll back up but some people might miss this)

**Comment by rocketeerbkw** [comment]
This is the same behavior for all react linked pages, so fixing globally should be the solution

**Comment by ccjjmartin** [comment]
Fixed closing
