### ISSUE TITLE
Create "Visit San Antonio" page

### ISSUE THREAD

**Issue by rocketeerbkw** [TexasCamp/2019.texascamp.org#5]
Create a page for san antonio similar to last years https://2018.texascamp.org/austin

**Comment by ccjjmartin** [comment]
Image for the San Antonio webpage:

![image](https://user-images.githubusercontent.com/12279982/64578406-eaadb400-d344-11e9-9ab3-2fceea5981b7.png)

**Comment by ccjjmartin** [comment]
From Art:

Great Restaurants nearby: Acenar, Playland pizza, La Panaderia, Bohanans, Paesanos,

**Comment by WidgetsBurritos** [comment]
@ccjjmartin here's a map:
https://drive.google.com/open?id=1enlM57RKa2kzBLzYIwhtKuY7UN7I_GOY&usp=sharing

If we want to try embedding into the site we can use this: 
```html
<iframe src="https://www.google.com/maps/d/u/1/embed?mid=1enlM57RKa2kzBLzYIwhtKuY7UN7I_GOY" width="640" height="480"></iframe>
```

I'm uncertain of the responsiveness of that map though.

**Comment by WidgetsBurritos** [comment]
@ccjjmartin Here's a first pass at the content for that page.  I don't have access to the CMS or else I'd post it in there myself: 

```html
<h2>Welcome to San Antonio</h2>

<p>San Antonio is the seventh-largest city in the United States. With a rich history and culture, and a rapidly growing market, it is a great mix of the old and new.</p>

<h2>Venue</h2>

<p><strong>Codeup</strong><br />
600 Navarro St #600<br />
San Antonio, TX 78205<br />
Just three short blocks from the Alamo.<br />
<a href="https://www.google.com/maps/dir//Codeup,+600+Navarro+St+%23600,+San+Antonio,+TX+78205" rel="noopener noreferrer" target="_blank">Get map/directions</a></p>

<p>TODO: PICTURE OF ENTRANCE GOES HERE</p>

<h2>Parking</h2>

<p><strong>St. Mary's Garage</strong><br />
400 N St Mary's St<br />
San Antonio, TX 78205</p>

<ul>
	<li>Flat Rate (Weekdays) - $10</li>
	<li>Flat Rate (Weeknights and Weekends) - $5</li>
</ul>

<h2>Hotels, Restaurants, Drinks and Attractions</h2>

<p>Interested in what San Antonio has to offer? Need a restaurant or hotel recommendation? Looking for a place to unwind after a long day at Texas Camp?</p>

<p>View our <a href="https://drive.google.com/open?id=1enlM57RKa2kzBLzYIwhtKuY7UN7I_GOY&amp;usp=sharing" rel="noopener noreferrer" target="_blank">interactive map of the city</a>.</p>

<p><iframe height="600" src="https://www.google.com/maps/d/u/1/embed?mid=1enlM57RKa2kzBLzYIwhtKuY7UN7I_GOY" width="100%"></iframe></p>

```

Note: This is both linking and attempting to embed the map.  I'd imagine we'd want to choose one or the other.  

Also, I'm unsure if you've got a good picture of the front door of Codeup or not. I left the placeholder there.

**Comment by ccjjmartin** [comment]
Added picture of the entrance

**Comment by ccjjmartin** [comment]
One the PR above is merged this issue can be closed.

**Comment by ccjjmartin** [comment]
I merged the PR to dev and it should go out soon, so I am closing this issue.  @WidgetsBurritos Thanks for your work on this.
