### ISSUE TITLE
Create "getting around" page.

### ISSUE THREAD

**Issue by WidgetsBurritos** [TexasCamp/2019.texascamp.org#56]
This page was created here: https://2019.texascamp.org/getting-around

There's also a PR #55 for adding the alamo to this page.

This page should be linked to from the Visiting San Antonio page.

**Comment by ccjjmartin** [comment]
@WidgetsBurritos I am going to close this as you already merged the PR and linked the page.  Feel free to reopen it if you think it needs to be reopened.
