### ISSUE TITLE
Schedule page broken

### ISSUE THREAD

**Issue by rocketeerbkw** [TexasCamp/2019.texascamp.org#60]
In some cases, it's not possible to load the Friday schedule. There are a couple diff JS errors being thrown

**Comment by ccjjmartin** [comment]
@rocketeerbkw Are you able to reproduce the Friday tab not loading?

**Comment by rocketeerbkw** [comment]
Not reliably, hence "in same cases." It came in as a bug report to our email, and when I checked then it was broken. But looking now, it's working. So... needs to be investigated

**Comment by rocketeerbkw** [comment]
If you load any other page, then click to the schedule it works fine. If you load the schedule directly there are JS errors which prevent the day tabs working correctly

**Comment by rocketeerbkw** [comment]
#61
