### ISSUE TITLE
Create homepage news

### ISSUE THREAD

**Issue by rocketeerbkw** [TexasCamp/2019.texascamp.org#7]
In order to take up space, one or two news articles should be written. We can take cues from 2018 and post something about last year and info about this year.

**Comment by ccjjmartin** [comment]
Irma Martin is going to look into this

**Comment by ccjjmartin** [comment]
She wrote one, I wrote the other.  Currently the one I wrote is in review

**Comment by ccjjmartin** [comment]
Created 2 news articles, technically one of them is a blocker but it related to issue #10 which I am marking as a launch blocker and closing this one.
